import type { Metadata } from "next";
import { ReactNode } from "react";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import theme from "./theme";
import Typography from "@mui/material/Typography";
import { Roboto } from 'next/font/google';
import {AppBar, Box, Container, Menu, MenuItem} from "@mui/material";
import ReduxProvider from "./store";
import Link from "next/link";

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
    </head>

    <ReduxProvider>
      <body className={roboto.variable}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <Container>
              <AppBar>
                  <Typography variant={"h4"}>1chan</Typography>
              </AppBar>
              <br/>
              <br/>
              <br/>
              <Link href="/dev/redux">Redux</Link>
              <Link href="/">Home</Link>
              {children}
            </Container>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </ReduxProvider>
    </html>
  );
}
